research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

pipedream_idea_task:
  description: >
    Conduct a thorough research on the Pipedream.com websites about {topic}
  expected_output: >
    An outline of how Pipedream.com can solve issues related to {topic}
  agent: pipedream_expert

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
    Please always output Markdown.
    You SHOULD include code snippets where those snippets are included in docs.
  agent: reporting_analyst
