research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

pipedream_idea_task:
  description: >
    Conduct a thorough research on the Pipedream.com websites about {topic}
  expected_output: >
    An outline of how Pipedream.com can solve issues related to {topic}
  agent: pipedream_expert

writing_task:
  description: >
    Review the context you got and create a story around how Pipedream can solve issues involved with {topic}.
    The story should be in a blog post format where there is an overarching problem that is solved step by step.
  expected_output: >
    A blog post formatted as markdown
    You SHOULD include code snippets where those snippets are included in docs.
    You should create a blog images with DallE similar to previous blog posts
  agent: blog_writer
